name: Main

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: "Test"
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Import Developer ID Certificate
        uses: wpilibsuite/import-signing-certificate@v1
        with:
          certificate-data: ${{ secrets.APPLE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
      - name: Set Keychain Lock Timeout
        run: security set-keychain-settings -lut 3600
      - name: Find all identities
        run: security find-identity
      - name: Build with Gradle
        run: ./gradlew build
      - name: Sign Libraries with Developer ID
        run: ./gradlew build -PdeveloperID=${{ secrets.APPLE_DEVELOPER_ID }}
      - uses: actions/upload-artifact@v2
        with:
          path: build/
